2023-04-30 14:38:47,400 - _internal.py:_log[line:113] - INFO:  * Running on http://localhost:1234/ (Press CTRL+C to quit)
2023-04-30 14:38:58,037 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 14:38:58] "[32mGET /device/data?perPage=10&page=1 HTTP/1.1[0m" 302 -
2023-04-30 14:38:58,059 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 14:38:58] "[37mGET /login/index HTTP/1.1[0m" 200 -
2023-04-30 14:39:01,157 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 14:39:01] "[32mGET /login/index?Username=root&Password=88888888 HTTP/1.1[0m" 302 -
2023-04-30 14:39:01,458 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 14:39:01] "[37mGET /device/index HTTP/1.1[0m" 200 -
2023-04-30 14:39:02,005 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 14:39:02] "[37mGET /device/data_operation?page=1&perPage=10 HTTP/1.1[0m" 200 -
2023-04-30 14:39:03,051 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 14:39:03] "[37mGET /device/data HTTP/1.1[0m" 200 -
2023-04-30 14:39:03,356 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 14:39:03] "[37mGET /device/data_operation?perPage=10&page=1 HTTP/1.1[0m" 200 -
2023-04-30 14:39:07,668 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 14:39:07] "[37mGET /device/file_operation/upload?page=1&perPage=10 HTTP/1.1[0m" 200 -
2023-04-30 14:39:11,682 - views.py:add_device_task_to_db[line:312] - CRITICAL: mdevicelistÂ§ßÂ∞è0
2023-04-30 14:39:11,684 - views.py:add_device_task_to_db[line:316] - ERROR: Task Error: Â∞ùËØïÂèëÂ∏É‰ªªÂä°ÔºàÊñá‰ª∂160ÔºâÂà∞ËÆæÂ§á1Ôºå ÈîôËØØÂéüÂõ†list index out of range
2023-04-30 14:39:11,700 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 14:39:11] "[37mPOST /device/task_operation/1 HTTP/1.1[0m" 200 -
2023-04-30 14:39:12,022 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 14:39:12] "[37mGET /device/data_operation?perPage=10&page=1 HTTP/1.1[0m" 200 -
